# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
config {
  module = true
}
plugin "terraform" {
  enabled = true
  version = "0.10.0"
  source = "github.com/terraform-linters/tflint-ruleset-terraform"
  preset = "all"
}
plugin "google" {
  enabled = true
  version = "0.30.0"
  source = "github.com/terraform-linters/tflint-ruleset-google"
}
plugin "aws" {
  enabled = true
  version = "0.37.0"
  source = "github.com/terraform-linters/tflint-ruleset-aws"
}
rule "terraform_documented_variables" {
  enabled = false
}
rule "terraform_documented_outputs" {
  enabled = false
}
